### ISSUE TITLE
The App still doesn't work on my phone

### ISSUE THREAD

**Issue by htl-leonding** [htl-leonding/2015_fiply#26]
After fresh cloning the repo, the app is still crashing

**Comment by DenkerMayr** [comment]
Does that still happen after deinstalling all previous versions of our app on your device?
There are some sections of code which are only executed upon the first start.
If there is a previous version of the app it may lead to an error.

**Comment by htl-leonding** [comment]
After deinstalling, and deleting all files the errors still exists
On the emulator it's not working, even the app was never deployed ther
Error
02-16 17:33:33.611: E/AndroidRuntime(2774): Caused by: android.database.sqlite.SQLiteException: **no such table: phasen** (code 1): , while compiling: DELETE FROM phasen
02-16 17:33:33.611: E/AndroidRuntime(2774): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)

**Comment by DenkerMayr** [comment]
We fail to reproduce this error but we are going to commit some code later this evening.
Please tell us if this does or doesn't fix the problem as we can't reproduce this scenario.

**Comment by htl-leonding** [comment]
Oh, a new error. this time you forgot a comma.
Caused by: android.database.sqlite.SQLiteException: near "nullplanid": syntax error (code 1): , while compiling: create table phasen (_id integer primary key autoincrement, startdate text not null, enddate text not null, phasenname text not null, phasendauer text not null, pausendauer text not null, saetze text not null, wiederholungen text not null**planid** text not null);  <-- Comma missing after null before planid

**Comment by DenkerMayr** [comment]
Added the missing Comma.

**Comment by htl-leonding** [comment]
Finally it's possible to start the app.
